#!/usr/bin/env python3
"""LESSONS.md — every lesson this system has ever learned, in ONE file.

HIS ASK, 2026-08-07:
    "help me compile it all in one file, so the new chat doesnt get confuse which
     lessons file should it analyze compile all the lessons from A-Z and from previous
     generations in one file so when the new chat opens it it automatically will
     understand what to avoid and what to fix without going through so many hastle"

    python tools/lessons_book.py            writes LESSONS.md at the repo root
    python tools/lessons_book.py --check    non-zero exit if LESSONS.md is stale

THE ONE RULE ABOUT THIS FILE: it is GENERATED, never hand-edited.
`ledgers/knowledge.json` remains the single source of truth — `planqc` 23 blocks a plan
whose LESSONS_ACK is below the ledger's count, and `tools/lessonize.py` is the only
thing that writes to it. A hand-typed copy of a ledger goes stale, and a stale ledger is
the exact bug class that has cost this repo the most (SYSTEM-MAP section 6). So this
file carries the ledger's own counts and a regeneration stamp; if they disagree with
`lessonize.py --status`, THIS FILE IS WRONG and must be regenerated.

Re-run it after every `lessonize.py` write. It costs nothing.
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(HERE, "ledgers", "knowledge.json")
OUT = os.path.join(HERE, "LESSONS.md")

# Themes are assigned by keyword, mechanically. A lesson matching nothing lands in
# "everything else" rather than being silently dropped — a dropped lesson is worse
# than an untidy one.
THEMES = [
    ("MEASUREMENT AND ITS TRAPS",
     ("measur", "smooth number", "vacuous", "approval band", "luma", "estimate",
      "calibrat", "provenance", "threshold", "open-loop", "delivered window")),
    ("IDENTITY, TEXT AND THINGS THE MODEL INVENTS",
     ("identity", "badge", "signage", "invented", "text", "plate", "wardrobe",
      "shirt", "face", "ocr", "veto", "j4")),
    ("LIGHT AND GRADE",
     ("light", "relight", "exposure", "grade", "bright", "dark", "shot_match",
      "gaffer")),
    ("SOUND AND MUSIC",
     ("sound", "audio", "foley", "bed", "bpm", "duck", "mix", "loud", "sfx",
      "music", "tempo")),
    ("THE CUT — LINKAGE, REPETITION, PACING",
     ("linkage", "carry", "consequence", "repeat", "duplicat", "crop", "blend",
      "whip", "transition", "beat", "pacing", "hook", "clock", "monotonic")),
    ("PROMPTS AND GENERATION",
     ("prompt", "generat", "preset", "reference image", "seedance", "negative",
      "plate prompt", "clip")),
    ("PIPELINE, TOOLING AND THE CONTRACT",
     ("engine.py", "planqc", "verify", "clipqc", "board.py", "smoketest", "font",
      "path", "glob", "contract", "inert", "silent default", "sandbox", "import")),
    ("PROCESS — HOW WE WORK TOGETHER",
     ("contact sheet", "look", "his call", "session", "resume", "doctrine",
      "approval scope", "handover", "ask", "standing order")),
]


def theme_of(text):
    low = text.lower()
    for name, keys in THEMES:
        if any(k in low for k in keys):
            return name
    return "EVERYTHING ELSE"


def split(lesson):
    """A lesson is 'YYYY-MM-DD HEADLINE: body'. Return (date, headline, body)."""
    m = re.match(r"^(\d{4}-\d{2}-\d{2})\s+(.*)$", lesson.strip(), re.S)
    date, rest = (m.group(1), m.group(2)) if m else ("", lesson.strip())
    m2 = re.match(r"^([^:.]{8,120})[:.]\s+(.*)$", rest, re.S)
    head, body = (m2.group(1), m2.group(2)) if m2 else (rest[:110], rest[110:])
    return date, " ".join(head.split()), " ".join(body.split())


def build():
    d = json.load(open(LEDGER, encoding="utf-8"))["topics"]
    topics = {k: (v.get("lessons") or []) for k, v in d.items()}
    total = sum(len(v) for v in topics.values())
    order = ["general craft"] + sorted(k for k in topics if k != "general craft")

    L = []
    a = L.append
    a("# LESSONS — everything this system has learned, in one file")
    a("")
    a("### GENERATED by `tools/lessons_book.py` from `ledgers/knowledge.json`. "
      "**Never edit this file by hand.**")
    a(f"### {total} lessons across {len(topics)} topics.")
    a("")
    a("`ledgers/knowledge.json` is the source of truth: `planqc` check 23 BLOCKS any "
      "plan whose `LESSONS_ACK` is below a topic's count, and `tools/lessonize.py` is "
      "the only thing that writes to it. If the counts below disagree with "
      "`python tools/lessonize.py --status`, **this file is stale — regenerate it.**")
    a("")
    a("```")
    a("LESSONS_ACK = {")
    for t in order:
        a(f'    "{t}": {len(topics[t])},')
    a("}")
    a("```")
    a("")
    a("---")
    a("")
    a("## HOW TO USE THIS FILE IN A NEW CHAT")
    a("")
    a("Read **THE TEN THAT COST US MOST** below. That is the whole briefing — it is "
      "what a fresh session needs to avoid repeating the expensive mistakes. Then use "
      "the per-topic sections as a reference while planning, and put every lesson that "
      "can touch the build you are about to make into that plan's `PREMORTEM` with its "
      "mitigation. **An ack is a claim that you read them; the premortem is the "
      "evidence.** `planqc` 23 checks a NUMBER, not comprehension — nothing can force "
      "the reading except you.")
    a("")
    a("---")
    a("")
    a("## THE TEN THAT COST US MOST")
    a("")
    a("Ordered by what they cost, not by date.")
    a("")
    for n, (title, why) in enumerate([
        ("LOOK AT A CONTACT SHEET BEFORE ANYTHING IS ASSEMBLED",
         "One 20-panel sheet caught what FOUR rounds of independent LLM judges reading "
         "prose could not: three different shirts on the persona, an invented sign "
         "board, a wrong-shaped waterfall, six duplicate framings. `tools/contact.py`, "
         "at ingest, before a frame is assembled. **His standing order.**"),
        ("SOURCE LIGHTING IS TRUSTED — THE RELIGHT PATH IS THE DEFECT",
         "He has said this TWICE (2026-08-05 and 2026-08-07). His approval band is 47 "
         "luma WIDE. Do not 'fix' an exposure spread; v14 bought a smooth number by "
         "moving one of his approved shots +72 luma. travel_vlog `shot_match_max_move` "
         "is now 0.0."),
        ("A NAMED SUBJECT IS NEVER GENERATED FROM TEXT ALONE",
         "A text-only '2026 Toyota Crown' returned a generic crossover and shipped an "
         "87cr wrong-car build. Plate first, at 4k, **LOOK AT IT**, then pass it as a "
         "reference on every shot."),
        ("A DECLARATION AND ITS READER MUST AGREE, OR NOTHING WILL SAY SO",
         "`engine.py` read `SOUND['hero_shot']`; crown defined `'hero'`. The only sound "
         "in a 30s film would have played 14.00s early on a 278cr build. Same shape: a "
         "wardrobe spec that lived only in the plate and was never read by the "
         "generator. Run `bugsense --class 1` before any credit moves."),
        ("MEASURE THE BALANCE, NEVER ESTIMATE",
         "A past estimate was off by 352cr. On 2026-08-07 the model was finally checked "
         "against a real transaction: `cost()` said 214.5 and the balance moved 214.50."),
        ("A CHECK THAT MEASURES NOTHING PRINTS OK",
         "8 of 13 checks once passed vacuously. A green tick is not evidence; the "
         "number behind it is. File 27 PART C holds all 16 traps — and an ANALYST can "
         "run them just as easily as a tool can."),
        ("A DIFFERENT CROP IS NOT A DIFFERENT PICTURE",
         "`planqc` 8 passed mahua and it delivered six duplicate framings at up to "
         "0.975 histogram correlation. Only the two sources with real internal motion "
         "escaped. A static source earns ONE shot."),
        ("A NEGATIVE BLOCK DOES NOT STOP INVENTED TEXT",
         "An invented 'SR' badge shipped through 8 builds. Then a sign board shipped "
         "with 'no signage' in the prompt AND in the negative block. Catch text "
         "surfaces by EYE, on every clip, after generation."),
        ("A LINKAGE MUST BE FINDABLE IN BOTH SHOTS, AND FRAMES CONFIRM IT",
         "KK v15 shipped 19 prose linkages; the eye found 5 that landed. Words plan a "
         "linkage, frames confirm it. 13 carry kinds and a decidable test for each are "
         "in `28-linkage-master.md`."),
        ("FIVE FAILURES ON ONE PROBLEM — STOP AND ASK",
         "His rule, mechanised in `mastermind_loop.py`. Looping burns credits and "
         "attention. Rank the options, name the pick, hand him the call."),
    ], 1):
        a(f"**{n}. {title}**  ")
        a(f"{why}")
        a("")
    a("---")
    a("")

    for t in order:
        ls = topics[t]
        if not ls:
            continue
        a(f"## {t.upper()}  ({len(ls)} lessons)")
        a("")
        buckets = {}
        for i, raw in enumerate(ls):
            buckets.setdefault(theme_of(str(raw)), []).append((i, str(raw)))
        for name, _ in THEMES + [("EVERYTHING ELSE", ())]:
            if name not in buckets:
                continue
            a(f"### {name}")
            a("")
            for i, raw in sorted(buckets[name], key=lambda x: -x[0]):
                date, head, body = split(raw)
                a(f"**L{i} · {date}** — {head}")
                if body:
                    a("")
                    a(f"> {body}")
                a("")
        a("---")
        a("")

    a("*Regenerate after every `lessonize.py` write: `python tools/lessons_book.py`*")
    return "\n".join(L) + "\n", total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text, total = build()
    if a.check:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("LESSONS.md is STALE — run python tools/lessons_book.py")
            return 1
        print(f"LESSONS.md current ({total} lessons)")
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"  {total} lessons -> {OUT}")
    print("  GENERATED. Never edit by hand; ledgers/knowledge.json is the truth.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
